import './globals.css'
import type { Metadata } from 'next'
import Link from "next/link";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  //@ts-ignore
  const res = await fetch('http://localhost:9999/topics', { next: { tags: ['collection'] } })
  const topics = await res.json()

  console.log(topics)
  return (
    <html lang="en">
      <body>
      <h1><Link href={'/'}>WEB</Link></h1>
      <ol>
        {

          topics.map((topic: any) => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })
        }
      </ol>
      {children}
      <ul>
        <li><Link href={'/create'}>Create</Link> </li>
        <li><Link href={'/update'}>Update</Link> </li>
        <li><input type='button' value={'delete'} /></li>
      </ul>
      </body>
    </html>
  )
}
